"""add signals table

Revision ID: ada89c8d664e
Revises: b28d0d4f09e6
Create Date: 2026-05-19 20:47:28.256843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ada89c8d664e'
down_revision: Union[str, None] = 'b28d0d4f09e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('market_id', sa.String(length=80), nullable=False),
    sa.Column('edge_name', sa.String(length=40), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('market_price', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('fair_price', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('edge_value', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('strength', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('size_shares', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('notional_usd', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.condition_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_accepted'), 'signals', ['accepted'], unique=False)
    op.create_index(op.f('ix_signals_market_id'), 'signals', ['market_id'], unique=False)
    op.create_index('ix_signals_market_ts', 'signals', ['market_id', 'ts'], unique=False)
    op.create_index(op.f('ix_signals_ts'), 'signals', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_ts'), table_name='signals')
    op.drop_index('ix_signals_market_ts', table_name='signals')
    op.drop_index(op.f('ix_signals_market_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_accepted'), table_name='signals')
    op.drop_table('signals')
    # ### end Alembic commands ###
