"""initial markets and book_snapshots

Revision ID: b28d0d4f09e6
Revises: 
Create Date: 2026-05-19 20:26:25.820551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b28d0d4f09e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('condition_id', sa.String(length=80), nullable=False),
    sa.Column('gamma_id', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('clob_token_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('outcomes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_index(op.f('ix_markets_gamma_id'), 'markets', ['gamma_id'], unique=True)
    op.create_index(op.f('ix_markets_slug'), 'markets', ['slug'], unique=False)
    op.create_table('book_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.String(length=80), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('best_bid', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('best_ask', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('last_trade_price', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('spread', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('liquidity_num', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('volume_24hr', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('accepting_orders', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.condition_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_snapshots_market_id'), 'book_snapshots', ['market_id'], unique=False)
    op.create_index('ix_book_snapshots_market_ts', 'book_snapshots', ['market_id', 'ts'], unique=False)
    op.create_index(op.f('ix_book_snapshots_ts'), 'book_snapshots', ['ts'], unique=False)
    op.create_table('markets_active',
    sa.Column('condition_id', sa.String(length=80), nullable=False),
    sa.Column('rank', sa.BigInteger(), nullable=False),
    sa.Column('liquidity_num', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('volume_24hr', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['markets.condition_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_index(op.f('ix_markets_active_rank'), 'markets_active', ['rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_markets_active_rank'), table_name='markets_active')
    op.drop_table('markets_active')
    op.drop_index(op.f('ix_book_snapshots_ts'), table_name='book_snapshots')
    op.drop_index('ix_book_snapshots_market_ts', table_name='book_snapshots')
    op.drop_index(op.f('ix_book_snapshots_market_id'), table_name='book_snapshots')
    op.drop_table('book_snapshots')
    op.drop_index(op.f('ix_markets_slug'), table_name='markets')
    op.drop_index(op.f('ix_markets_gamma_id'), table_name='markets')
    op.drop_table('markets')
    # ### end Alembic commands ###
