"""add paper fills and portfolio state

Revision ID: ea96572a4bda
Revises: ada89c8d664e
Create Date: 2026-05-19 21:23:41.997393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea96572a4bda'
down_revision: Union[str, None] = 'ada89c8d664e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_state',
    sa.Column('market_id', sa.String(length=80), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('shares', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('total_fees_usd', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('n_fills', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.condition_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('market_id', 'side')
    )
    op.create_table('fills_paper',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('signal_id', sa.BigInteger(), nullable=False),
    sa.Column('market_id', sa.String(length=80), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('shares', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('mid_at_fill', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('slippage_bps', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('notional_usd', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('fees_usd', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.condition_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_paper_market_id'), 'fills_paper', ['market_id'], unique=False)
    op.create_index(op.f('ix_fills_paper_signal_id'), 'fills_paper', ['signal_id'], unique=False)
    op.create_index(op.f('ix_fills_paper_ts'), 'fills_paper', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fills_paper_ts'), table_name='fills_paper')
    op.drop_index(op.f('ix_fills_paper_signal_id'), table_name='fills_paper')
    op.drop_index(op.f('ix_fills_paper_market_id'), table_name='fills_paper')
    op.drop_table('fills_paper')
    op.drop_table('portfolio_state')
    # ### end Alembic commands ###
